export const LOGIN_PATH = "/login";
export const PLATFORM_PATH = "/platform";



export const QUESTIONNAIRES = "/questionnaires";

// ---- generated by questionnaireGenerator: ROUTELOCATIONS ----
export const QUESTIONNAIRES_ROUTELOCATIONS = QUESTIONNAIRES + "/routelocations";
// ---- end generated ----

// ---- generated by questionnaireGenerator: DEFAULTAGREEMENTPLANS ----
export const QUESTIONNAIRES_DEFAULTAGREEMENTPLANS = QUESTIONNAIRES + "/defaultagreementplans";
// ---- end generated ----

// ---- generated by questionnaireGenerator: CONTRACTTYPESSUBTYPES ----
export const QUESTIONNAIRES_CONTRACTTYPESSUBTYPES = QUESTIONNAIRES + "/contracttypes/subtypes";
// ---- end generated ----

// ---- generated by questionnaireGenerator: CONTRACTTOPICS ----
export const QUESTIONNAIRES_CONTRACTTOPICS = QUESTIONNAIRES + "/contracttopics";
// ---- end generated ----

// ---- generated by questionnaireGenerator: OWNERS ----
export const QUESTIONNAIRES_OWNERS = QUESTIONNAIRES + "/owners";
// ---- end generated ----
export const QUESTIONNAIRES_TOPIC = QUESTIONNAIRES + "/topic";
export const QUESTIONNAIRES_SUBTOPIC = QUESTIONNAIRES + "/subtopic";
export const QUESTIONNAIRES_EXECUTION_RULES =
  QUESTIONNAIRES + "/execution-rules";
export const QUESTIONNAIRES_DOCUMENT_RECIEVE_METHODS =
  QUESTIONNAIRES + "/document-recieve-methods";
export const QUESTIONNAIRES_DOCUMENT_TYPES = QUESTIONNAIRES + "/document-types";
export const QUESTIONNAIRES_COUNTRIES = QUESTIONNAIRES + "/countries";
export const QUESTIONNAIRES_STREETS = QUESTIONNAIRES + "/streets";
export const QUESTIONNAIRES_ORGANIZATIONS = QUESTIONNAIRES + "/organizations";
export const QUESTIONNAIRES_STRUCTURES = QUESTIONNAIRES + "/structures";
export const QUESTIONNAIRES_APPLICATION_FORMS =
  QUESTIONNAIRES + "/application-forms";
export const QUESTIONNAIRES_DOCUMENT_WHOM = QUESTIONNAIRES + "/document-whom";
export const QUESTIONNAIRES_MARGIN_NOTE_TEXTS =
  QUESTIONNAIRES + "/margin-note-texts";
export const QUESTIONNAIRES_DELIVERY_METHOD =
  QUESTIONNAIRES + "/delivery-method";
export const QUESTIONNAIRES_BRANDS = QUESTIONNAIRES + "/brands";
export const QUESTIONNAIRES_CHASSIS_TYPES = QUESTIONNAIRES + "/chassis-types";
export const QUESTIONNAIRES_COLORS = QUESTIONNAIRES + "/colors";
export const QUESTIONNAIRES_ENGINE_TYPES = QUESTIONNAIRES + "/engine-types";
export const QUESTIONNAIRES_GEARBOX_TYPES = QUESTIONNAIRES + "/gearbox-types";
export const QUESTIONNAIRES_ISSUED_AUTHORITIES =
  QUESTIONNAIRES + "/issued-authorities";
export const QUESTIONNAIRES_MODELS = QUESTIONNAIRES + "/models";
export const QUESTIONNAIRES_OWNERSHIP_TYPES =
  QUESTIONNAIRES + "/ownership-types";
export const QUESTIONNAIRES_TRANSMITTER_TYPES =
  QUESTIONNAIRES + "/transmitter-types";
export const QUESTIONNAIRES_VEHICLE_TYPES = QUESTIONNAIRES + "/vehicle-types";
export const QUESTIONNAIRES_ACADEMIC_DEGREES =
  QUESTIONNAIRES + "/academic-degrees";
export const QUESTIONNAIRES_DISABILITY_STATUSES =
  QUESTIONNAIRES + "/disability-statuses";
export const QUESTIONNAIRES_HONORARY_TITLES =
  QUESTIONNAIRES + "/honorary-titles";
export const QUESTIONNAIRES_MILITARY_STAFFS =
  QUESTIONNAIRES + "/military-staffs";
export const QUESTIONNAIRES_MILITARY_CATEGORIES =
  QUESTIONNAIRES + "/military-categories";
export const QUESTIONNAIRES_MILITARY_RANKS = QUESTIONNAIRES + "/military-ranks";
export const QUESTIONNAIRES_MILITARY_GROUPS =
  QUESTIONNAIRES + "/military-groups";
export const QUESTIONNAIRES_GENERAL_STRUCTURE_STATUSES =
  QUESTIONNAIRES + "/general-structure-statuses";
export const QUESTIONNAIRES_WORK_SCHEDULES = QUESTIONNAIRES + "/work-schedules";
export const QUESTIONNAIRES_SPECIALIZATIONS =
  QUESTIONNAIRES + "/specializations";
export const QUESTIONNAIRES_WAR_PARTICIPANTS =
  QUESTIONNAIRES + "/war-participants";
export const QUESTIONNAIRES_GENERAL_STRUCTURE_TYPES =
  QUESTIONNAIRES + "/general-structure-types";
export const QUESTIONNAIRES_EDUCATION_INSTITUTIONS =
  QUESTIONNAIRES + "/education-institutions";
export const QUESTIONNAIRES_EDUCATION_PAYMENTS =
  QUESTIONNAIRES + "/education-payments";
export const QUESTIONNAIRES_EDUCATION_LEVELS =
  QUESTIONNAIRES + "/education-levels";
export const QUESTIONNAIRES_REPRIMAND_TYPES =
  QUESTIONNAIRES + "/reprimand-types";
export const QUESTIONNAIRES_DRIVING_CATEGORIES =
  QUESTIONNAIRES + "/driving-categories";
export const QUESTIONNAIRES_EMPLOYEE_CONFIGURATIONS =
  QUESTIONNAIRES + "/employee-configurations";
export const QUESTIONNAIRES_SPECIAL_DAYS = QUESTIONNAIRES + "/special-days";
export const QUESTIONNAIRES_CATEGORIES = QUESTIONNAIRES + "/categories";
export const QUESTIONNAIRES_REGIONS = QUESTIONNAIRES + "/regions";
export const QUESTIONNAIRES_AREAS = QUESTIONNAIRES + "/areas";
export const QUESTIONNAIRES_COMPANIES = QUESTIONNAIRES + "/companies";
export const QUESTIONNAIRES_POSITIONS = QUESTIONNAIRES + "/positions";
export const QUESTIONNAIRES_HALLS = QUESTIONNAIRES + "/halls";


export const QUESTIONNAIRES_CONTRAGENTTYPES = QUESTIONNAIRES + "/contragenttypes";
export const QUESTIONNAIRES_CONTRACTTYPES = QUESTIONNAIRES + "/contracttypes";
export const QUESTIONNAIRES_CONTRACTCURRENCIES = QUESTIONNAIRES + "/contractcurrencies";
export const QUESTIONNAIRES_ORDERS = QUESTIONNAIRES + "/orders";

export const QUESTIONNAIRES_WORK_MODES = QUESTIONNAIRES + "/work-modes";

export const QUESTIONNAIRES_VEHICLE_CATEGORIES = QUESTIONNAIRES + "/vehicle-categories";
export const QUESTIONNAIRES_CHEMICALS = QUESTIONNAIRES + "/chemicals";

export const QUESTIONNAIRES_REPAIR_TYPES = QUESTIONNAIRES + "/repair-types";

export const QUESTIONNAIRES_DETAIL_PARTS = QUESTIONNAIRES + "/detail-parts";

export const QUESTIONNAIRES_MEASUREMENT_TYPES = QUESTIONNAIRES + "/measurement-types";


export const QUESTIONNAIRES_REPAIRMENT_WORK_TYPES = QUESTIONNAIRES + "/repairment-work-types";


export const QUESTIONNAIRES_PENALTY_TYPES = QUESTIONNAIRES + "/penalty-types";


export const QUESTIONNAIRES_CRUSH_REASONS = QUESTIONNAIRES + "/crush-reasons";

export const QUESTIONNAIRES_INSURANCE_TYPES = QUESTIONNAIRES + "/insurance-types";

export const QUESTIONNAIRES_EXTRA_SERVICES = QUESTIONNAIRES + "/extra-services";

export const QUESTIONNAIRES_FUEL_TYPES = QUESTIONNAIRES + "/fuel-types";

export const QUESTIONNAIRES_OIL_FIELDS = QUESTIONNAIRES + "/oil-fields";

export const QUESTIONNAIRES_VEHICLE_GROUPS = QUESTIONNAIRES + "/vehicle-groups";