export const LOGIN_PATH = "/login";
export const PLATFORM_PATH = "/platform";



export const QUESTIONNAIRES = "/questionnaires";

// ---- generated by questionnaireGenerator: VENDORCATEGORIES ----
export const QUESTIONNAIRES_VENDORCATEGORIES = "vendor/categories";
// ---- end generated ----

// ---- generated by questionnaireGenerator: INVENTORYTECHNICALDETAILS ----
export const QUESTIONNAIRES_INVENTORYTECHNICALDETAILS = "inventoryTechnicalDetails";
// ---- end generated ----

// ---- generated by questionnaireGenerator: INVENTORYPACKAGETYPES ----
export const QUESTIONNAIRES_INVENTORYPACKAGETYPES = "inventoryPackageTypes";
// ---- end generated ----

// ---- generated by questionnaireGenerator: INVENTORYMODELS ----
export const QUESTIONNAIRES_INVENTORYMODELS = "inventoryModels";
// ---- end generated ----

// ---- generated by questionnaireGenerator: INVENTORYCATEGORIES ----
export const QUESTIONNAIRES_INVENTORYCATEGORIES = "inventoryCategories";
// ---- end generated ----

// ---- generated by questionnaireGenerator: INVENTORYBRANDS ----
export const QUESTIONNAIRES_INVENTORYBRANDS = "inventoryBrands";
// ---- end generated ----

// ---- generated by questionnaireGenerator: CUSTOMERS ----
export const QUESTIONNAIRES_CUSTOMERS = "customers";
// ---- end generated ----

// ---- generated by questionnaireGenerator: PROJECTS ----
export const QUESTIONNAIRES_PROJECTS = "projects";
// ---- end generated ----

// ---- generated by questionnaireGenerator: PENTIONS ----
export const QUESTIONNAIRES_PENTIONS = "pentions";
// ---- end generated ----

// ---- generated by questionnaireGenerator: DEPARTMENTS ----
export const QUESTIONNAIRES_DEPARTMENTS = "departments";
// ---- end generated ----

// ---- generated by questionnaireGenerator: BUDGETCOMPONENTS ----
export const QUESTIONNAIRES_BUDGETCOMPONENTS = "budget-components";
// ---- end generated ----

// ---- generated by questionnaireGenerator: BARREL ----
export const QUESTIONNAIRES_BARREL = "barrels";
// ---- end generated ----

// ---- generated by questionnaireGenerator: WELL ----
export const QUESTIONNAIRES_WELL = "wells";
// ---- end generated ----

// ---- generated by questionnaireGenerator: FIELD ----
export const QUESTIONNAIRES_FIELD = "fields";
// ---- end generated ----

// ---- generated by questionnaireGenerator: INTERNALSTRUCTURE ----
export const QUESTIONNAIRES_INTERNALSTRUCTURE = "internalstructures";
// ---- end generated ----

// ---- generated by questionnaireGenerator: ROUTELOCATIONS ----
export const QUESTIONNAIRES_ROUTELOCATIONS = "routelocations";
// ---- end generated ----

// ---- generated by questionnaireGenerator: DEFAULTAGREEMENTPLANS ----
export const QUESTIONNAIRES_DEFAULTAGREEMENTPLANS = "defaultagreementplans";
// ---- end generated ----

// ---- generated by questionnaireGenerator: CONTRACTTYPESSUBTYPES ----
export const QUESTIONNAIRES_CONTRACTTYPESSUBTYPES = "contracttypes/subtypes";
// ---- end generated ----

// ---- generated by questionnaireGenerator: CONTRACTTOPICS ----
export const QUESTIONNAIRES_CONTRACTTOPICS = "contracttopics";
// ---- end generated ----

// ---- generated by questionnaireGenerator: OWNERS ----
export const QUESTIONNAIRES_OWNERS = "owners";
// ---- end generated ----
export const QUESTIONNAIRES_TOPIC = "topic";
export const QUESTIONNAIRES_SUBTOPIC = "subtopic";
export const QUESTIONNAIRES_EXECUTION_RULES =
  "execution-rules";
export const QUESTIONNAIRES_DOCUMENT_RECIEVE_METHODS =
  "document-recieve-methods";
export const QUESTIONNAIRES_DOCUMENT_TYPES = "document-types";
export const QUESTIONNAIRES_COUNTRIES = "countries";
export const QUESTIONNAIRES_STREETS = "streets";
export const QUESTIONNAIRES_ORGANIZATIONS = "organizations";
export const QUESTIONNAIRES_STRUCTURES = "structures";
export const QUESTIONNAIRES_APPLICATION_FORMS =
  "application-forms";
export const QUESTIONNAIRES_DOCUMENT_WHOM = "document-whom";
export const QUESTIONNAIRES_MARGIN_NOTE_TEXTS =
  "margin-note-texts";
export const QUESTIONNAIRES_DELIVERY_METHOD =
  "delivery-method";
export const QUESTIONNAIRES_BRANDS = "brands";
export const QUESTIONNAIRES_CHASSIS_TYPES = "chassis-types";
export const QUESTIONNAIRES_COLORS = "colors";
export const QUESTIONNAIRES_ENGINE_TYPES = "engine-types";
export const QUESTIONNAIRES_GEARBOX_TYPES = "gearbox-types";
export const QUESTIONNAIRES_ISSUED_AUTHORITIES =
  "issued-authorities";
export const QUESTIONNAIRES_MODELS = "models";
export const QUESTIONNAIRES_OWNERSHIP_TYPES =
  "ownership-types";
export const QUESTIONNAIRES_TRANSMITTER_TYPES =
  "transmitter-types";
export const QUESTIONNAIRES_VEHICLE_TYPES = "vehicle-types";
export const QUESTIONNAIRES_ACADEMIC_DEGREES =
  "academic-degrees";
export const QUESTIONNAIRES_DISABILITY_STATUSES =
  "disability-statuses";
export const QUESTIONNAIRES_HONORARY_TITLES =
  "honorary-titles";
export const QUESTIONNAIRES_MILITARY_STAFFS =
  "military-staffs";
export const QUESTIONNAIRES_MILITARY_CATEGORIES =
  "military-categories";
export const QUESTIONNAIRES_MILITARY_RANKS = "military-ranks";
export const QUESTIONNAIRES_MILITARY_GROUPS =
  "military-groups";
export const QUESTIONNAIRES_GENERAL_STRUCTURE_STATUSES =
  "general-structure-statuses";
export const QUESTIONNAIRES_WORK_SCHEDULES = "work-schedules";
export const QUESTIONNAIRES_SPECIALIZATIONS =
  "specializations";
export const QUESTIONNAIRES_WAR_PARTICIPANTS =
  "war-participants";
export const QUESTIONNAIRES_GENERAL_STRUCTURE_TYPES =
  "general-structure-types";
export const QUESTIONNAIRES_EDUCATION_INSTITUTIONS =
  "education-institutions";
export const QUESTIONNAIRES_EDUCATION_PAYMENTS =
  "education-payments";
export const QUESTIONNAIRES_EDUCATION_LEVELS =
  "education-levels";
export const QUESTIONNAIRES_REPRIMAND_TYPES =
  "reprimand-types";
export const QUESTIONNAIRES_DRIVING_CATEGORIES =
  "driving-categories";
export const QUESTIONNAIRES_EMPLOYEE_CONFIGURATIONS =
  "employee-configurations";
export const QUESTIONNAIRES_SPECIAL_DAYS = "special-days";
export const QUESTIONNAIRES_CATEGORIES = "categories";
export const QUESTIONNAIRES_REGIONS = "regions";
export const QUESTIONNAIRES_AREAS = "areas";
export const QUESTIONNAIRES_COMPANIES = "companies";
export const QUESTIONNAIRES_POSITIONS = "positions";
export const QUESTIONNAIRES_HALLS = "halls";


export const QUESTIONNAIRES_CONTRAGENTTYPES = "contragenttypes";
export const QUESTIONNAIRES_CONTRACTTYPES = "contracttypes";
export const QUESTIONNAIRES_CONTRACTCURRENCIES = "contractcurrencies";
export const QUESTIONNAIRES_ORDERS = "orders";

export const QUESTIONNAIRES_WORK_MODES = "work-modes";

export const QUESTIONNAIRES_VEHICLE_CATEGORIES = "vehicle-categories";
export const QUESTIONNAIRES_CHEMICALS = "chemicals";

export const QUESTIONNAIRES_REPAIR_TYPES = "repair-types";

export const QUESTIONNAIRES_DETAIL_PARTS = "detail-parts";

export const QUESTIONNAIRES_MEASUREMENT_TYPES = "measurement-types";


export const QUESTIONNAIRES_REPAIRMENT_WORK_TYPES = "repairment-work-types";


export const QUESTIONNAIRES_PENALTY_TYPES = "penalty-types";


export const QUESTIONNAIRES_CRUSH_REASONS = "crush-reasons";

export const QUESTIONNAIRES_INSURANCE_TYPES = "insurance-types";

export const QUESTIONNAIRES_EXTRA_SERVICES = "extra-services";

export const QUESTIONNAIRES_FUEL_TYPES = "fuel-types";

export const QUESTIONNAIRES_OIL_FIELDS = "oil-fields";

export const QUESTIONNAIRES_VEHICLE_GROUPS = "vehicle-groups";