export const LOGIN_PATH = "/login";
export const PLATFORM_PATH = "/platform";


export const SETTINGS_PATH = "/settings";
export const SETTINGS_PERMISSIONS = SETTINGS_PATH + "/permissions";


export const SETTINGS_QUESTIONNAIRES = SETTINGS_PATH + "/questionnaires";
export const SETTINGS_QUESTIONNAIRES_TOPIC = SETTINGS_QUESTIONNAIRES + "/topic";
export const SETTINGS_QUESTIONNAIRES_SUBTOPIC =
  SETTINGS_QUESTIONNAIRES + "/subtopic";
export const SETTINGS_QUESTIONNAIRES_EXECUTION_RULES =
  SETTINGS_QUESTIONNAIRES + "/execution-rules";
export const SETTINGS_QUESTIONNAIRES_DOCUMENT_RECIEVE_METHODS =
  SETTINGS_QUESTIONNAIRES + "/document-recieve-methods";
export const SETTINGS_QUESTIONNAIRES_DOCUMENT_TYPES =
  SETTINGS_QUESTIONNAIRES + "/document-types";
export const SETTINGS_QUESTIONNAIRES_COUNTRIES =
  SETTINGS_QUESTIONNAIRES + "/countries";
export const SETTINGS_QUESTIONNAIRES_STREETS =
  SETTINGS_QUESTIONNAIRES + "/streets";
export const SETTINGS_QUESTIONNAIRES_ORGANIZATIONS =
  SETTINGS_QUESTIONNAIRES + "/organizations";
export const SETTINGS_QUESTIONNAIRES_STRUCTURES =
  SETTINGS_QUESTIONNAIRES + "/structures";
export const SETTINGS_QUESTIONNAIRES_APPLICATION_FORMS =
  SETTINGS_QUESTIONNAIRES + "/application-forms";
export const SETTINGS_QUESTIONNAIRES_DOCUMENT_WHOM =
  SETTINGS_QUESTIONNAIRES + "/document-whom";
export const SETTINGS_QUESTIONNAIRES_MARGIN_NOTE_TEXTS =
  SETTINGS_QUESTIONNAIRES + "/margin-note-texts";
export const SETTINGS_QUESTIONNAIRES_DELIVERY_METHOD =
  SETTINGS_QUESTIONNAIRES + "/delivery-method";


export const DOCUMENT_CIRCULATION_QUESTIONNAIRES =
  "/questionnaires";
export const DOCUMENT_CIRCULATION_QUESTIONNAIRES_TOPIC =
  DOCUMENT_CIRCULATION_QUESTIONNAIRES + "/topic";
export const DOCUMENT_CIRCULATION_QUESTIONNAIRES_SUBTOPIC =
  DOCUMENT_CIRCULATION_QUESTIONNAIRES + "/subtopic";
export const DOCUMENT_CIRCULATION_QUESTIONNAIRES_EXECUTION_RULES =
  DOCUMENT_CIRCULATION_QUESTIONNAIRES + "/execution-rules";
export const DOCUMENT_CIRCULATION_QUESTIONNAIRES_DOCUMENT_RECIEVE_METHODS =
  DOCUMENT_CIRCULATION_QUESTIONNAIRES + "/document-recieve-methods";
export const DOCUMENT_CIRCULATION_QUESTIONNAIRES_DOCUMENT_TYPES =
  DOCUMENT_CIRCULATION_QUESTIONNAIRES + "/document-types";
export const DOCUMENT_CIRCULATION_QUESTIONNAIRES_COUNTRIES =
  DOCUMENT_CIRCULATION_QUESTIONNAIRES + "/countries";
export const DOCUMENT_CIRCULATION_QUESTIONNAIRES_STREETS =
  DOCUMENT_CIRCULATION_QUESTIONNAIRES + "/streets";
export const DOCUMENT_CIRCULATION_QUESTIONNAIRES_ORGANIZATIONS =
  DOCUMENT_CIRCULATION_QUESTIONNAIRES + "/organizations";
export const DOCUMENT_CIRCULATION_QUESTIONNAIRES_STRUCTURES =
  DOCUMENT_CIRCULATION_QUESTIONNAIRES + "/structures";
export const DOCUMENT_CIRCULATION_QUESTIONNAIRES_APPLICATION_FORMS =
  DOCUMENT_CIRCULATION_QUESTIONNAIRES + "/application-forms";
export const DOCUMENT_CIRCULATION_QUESTIONNAIRES_DOCUMENT_WHOM =
  DOCUMENT_CIRCULATION_QUESTIONNAIRES + "/document-whom";
export const DOCUMENT_CIRCULATION_QUESTIONNAIRES_MARGIN_NOTE_TEXTS =
  DOCUMENT_CIRCULATION_QUESTIONNAIRES + "/margin-note-texts";
export const DOCUMENT_CIRCULATION_QUESTIONNAIRES_DELIVERY_METHOD =
  DOCUMENT_CIRCULATION_QUESTIONNAIRES + "/delivery-method";
export const DOCUMENT_CIRCULATION_BRANDS =
  DOCUMENT_CIRCULATION_QUESTIONNAIRES + "/brands";
